compartment_id: "ocid1.compartment.oc1..aaaaaaaagqvd5cybmsllqqkbligbbij6oueegrkrjyusjfikqnvdpovs0laq"

shared_dag_config:
  retries: 3
  retry_delay: 300
  max_active_runs: 1
  catchup: false
  start_date: "2024-11-20T00:00:00"
  run_poll_interval: 60

shared_dataflow_config:
  driver_shape: "VM.Standard.E4.Flex"
  executor_shape: "VM.Standard.E4.Flex"

  driver_shape_config:
    ocpus: 2
    memory_in_gbs: 16

  executor_shape_config:
    ocpus: 2
    memory_in_gbs: 16

  num_executors: 2

dag_configs:
  aggregation:
    dag_id: "airflow_dag_p6_pds_to_oci"
    description: "P6 PDS to OCI ADW via DataFlow"
    schedule_interval: "0 1 * * *"
    pipeline_apps:
      - "application_id_p6_pds_to_oci"

Applications:
  details:
    # DataFlow application OCID
    application_id_p6_pds_to_oci: "ocid1.dataflowapplication.oc1.me-jeddah-1.YOUR_FULL_APP_OCID_HERE"

    # Display name for the run
    p6_pds_to_oci_display_name: "p6_pds_to_oci_run"

dataflow_app:
  - logs_bucket_uri: "oci://bkt-neom-enowa-synergyze-dev-data-operations@axjj8sdvrg1w/dataflow-applications/logs/"
    configuration: {}
